name: JUCE Private Build

on:
  workflow_dispatch:
    inputs:
      triggerer:
        required: false
        type: string
        default: ''
        description: The GitHub ID to receive email notifications (leave blank)
      nightly-targets:
        required: false
        type: string
        default: "[]"
        description: A list of nightly build targets in JSON format
      cpp-std:
        required: false
        type: string
        default: ""
        description: The C++ standard to use (optional [20, 23])

run-name: "[${{ inputs.triggerer && inputs.triggerer || github.event.sender.login }}] ${{ github.sha }}"

jobs:
  build:
    name: .
    # Not having the ability to do a dynamic 'uses' call is a real pain. To
    # test some new CI configuration you must set the branch in both places
    # below.
    uses: juce-framework/JUCE-utils/.github/workflows/main.yml@master
    with:
      juce-utils-branch: master
      nightly-targets: ${{ inputs.nightly-targets }}
      triggerer: ${{ inputs.triggerer && inputs.triggerer || github.event.sender.login }}
      cpp-std: ${{ inputs.cpp-std }}
    secrets: inherit
  deploy:
    if: ${{ contains(fromJSON('["master", "develop"]'), github.ref_name) && inputs.cpp-std == '' && inputs.nightly-targets == '[]' }}
    needs: [build]
    name: Deploy
    uses: juce-framework/JUCE-utils/.github/workflows/deploy.yml@master
    secrets: inherit
  docs:
    if: ${{ contains(fromJSON('["master", "develop"]'), github.ref_name) && inputs.cpp-std == '' && inputs.nightly-targets == '[]' }}
    needs: [deploy]
    name: Docs
    uses: juce-framework/JUCE-utils/.github/workflows/docs.yml@master
    secrets: inherit
  notify:
    if: ${{ !(cancelled() || failure()) && inputs.nightly-targets == '[]' }}
    needs: [docs]
    name: Notify
    uses: juce-framework/JUCE-utils/.github/workflows/notify.yml@master
    with:
      triggerer: ${{ inputs.triggerer && inputs.triggerer || github.event.sender.login }}
    secrets: inherit

